### ISSUE TITLE
404 Http Error

### ISSUE THREAD

**Issue by GramDev1** [RobertSmith/Orchestrate.NET#30]
I am getting a 404 error while contacting the api. Tried with Curl, no error.

**Comment by OutdatedVersion** [comment]
Could you provide more troubleshooting details? A simple "I'm getting so and so" doesn't really allow proper diagnostics for your issue. ;)

**Comment by mcjp78** [comment]
Did you attempt to use this version? I'd so peek at the Java version, I know you hate vs.

P.S: this is my language and im pretty sure this library is dead :(

**Comment by OutdatedVersion** [comment]
Of course I didn't use this. That wouldn't make any sense?

**Comment by RobertSmith** [comment]
I am having no issues using this version. If you are still having problems please open a new issue and post some sample code. Thanks!
